name: Combined Workflow

on:
  schedule:
    - cron: '0 */6 * * *'  # Schedule to run every 6 hours
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-calendar:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create working directory
        run: |
          rm -rf ./files
          mkdir ./files

      - name: Run the script
        run: python main.py

      - name: Commit and push the generated .ics
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./files/kantine-kalender.ics
          git commit -am "Add generated .ics file" || echo "No changes to commit"
          git push

  deploy-calendar:
    needs: generate-calendar  # Specify the dependency on generate-calendar job
    environment:
      name: github-pages
      url: https://kbhkantine.victorbuch.dk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './files'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
