name: Run Every 6 hours

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create working directory
        run: |
          mkdir ./files

      - name: Run the script
        run: python main.py

      - name: Commit and push the generated .ics
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./files/kantine-kalender.ics
          git commit -am "Add generated .ics file" || echo "No changes to commit"
          git push
